### ISSUE TITLE
FuguHub: Test install to find about logging, location

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#238]
FuguHub: Lightweight WebDAV cloud (eg: dropbox) with a CMS (only in `dietpi-software`).

Result of test will be used in issue #239.

**Comment by MichaIng** [comment]
### Interactive install
1. Press ENTER to continue
2. Press y to accept license
3. Press y for VPS and n for home/office server
4. Choose whether to install an internal BitTorrent client ... Ah it's a Transmission daemon build hosted on their server. It doesn't make much sense, could even conflict with our implementation. I'll see this question can be removed or pre-answered.
**EDIT: Ah it runs the Transmission daemon as a child process. Hmm, bad since DietPi will start it as dedicated system service as well 🤔. Probably it should be masked to not interfere.**
### Logging
- Service: `journalctl -u bdd`
- Trace: `/home/bd/trace/` # It contains an info about the database creation only, even after playing around with the web UI a bid.
### Web access
- `http://<yourIP>/` # Yes it runs on port 80 and optional 443, hence is incompatible with a regular webserver with default setup.
- On first access, an admin account needs to be created to log in with for full control.
### Install directory: `/home/bd`
### Data directory: `/mnt/dietpi_userdata/fuguhub-data`
### Config file: `/home/bd/bdd.conf`
