### ISSUE TITLE
Clonezilla for BIOS - nativePC & SD card

### ISSUE THREAD

**Issue by fpetru** [MichaIng/DietPi-Docs#260]

**Comment by fpetru** [comment]
Rufus to choose not GPT.

**Comment by MichaIng** [comment]
Yes exactly. Both installer images (GPT/UEFI and MBR/BIOS) can be installed exactly the same way, with the small but important difference that the UEFI image needs to be flashed with GPT partition table and the BIOS image with MBR, to assure itself is booted in right mode (not all UEFI machines even support MBR boot, especially those mini/Atom PCs) and the internal disk will be formatted with GPT partition table as well.

Can this choice (GPT/MBR) be done with Etcher as well, actually?

**Comment by fpetru** [comment]
@MichaIng - yes balenaEtcher should be able to write also MBR/BIOS images. I've detected a configuration in the logs `hasMBR”:true"`, `"hasGPT":false` so it should be automatically aware of the type. Do you think you could give it a try ? 

Following your answer I can extend the guides - both using Rufus, as well as Etcher.

**Comment by MichaIng** [comment]
Once DietPi v6.34 is finished I'll have a look at this. Two more tasks came on top of what needs to be done, so I'm busy the next days 😄.

**Comment by StephanStS** [comment]
Idea: Add a new tab instead of mixing it into the existing UEFI tab.

**Comment by MichaIng** [comment]
Yes, as discussed: Let's simply create a separate tab for each download type:
- BIOS/MBR direct flash image
- UEFI/GPT direct flash image (there are some as well, which is not really outlined yet, e.g. ROCK Pi S)
- BIOS/MBR installer image
- UEFI/GPT installer image
- VirtualBox
- VMware
- Hyper-V (mid-term)
- ESXi (long-term)

Has someone a better idea how the image type can be named that is flashed to the OS root drive directly? "SD card image" does not really fit as it can be flashed on any other type of drive, usually, e.g. internal eMMC or external SSD/stick, in case of PC whatever system drive it has.

I'd switch to a consistent naming on the download page as well then, so that, along with the link, one can easily find the correct tab in the docs.

**Comment by StephanStS** [comment]
Proposals:
- Root drive image
- Root image
