### ISSUE TITLE
Add a Debian installer howto

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#377]
The Debian mini.iso installer is a great way to create a minimal bootable Debian system and it meanwhile supports some SBCs as well. It hence would be great if we could provide a step-by-step guide about how to use it. As an orientation, the x64_64/VM image creation instructions from the DietPi GitHub wiki can be used: https://github.com/MichaIng/DietPi/wiki/How-to-create-a-DietPi-image-for-x86_64-PCs-(UEFI)

**Comment by StephanStS** [comment]
@MichaIng: Is this issue actual? Or is it obsolete due to the automatic image generation?
Who would be the stakeholder reading this howto?

**Comment by MichaIng** [comment]
Good question. It probably would still have some value to have this documented somewhere, even if its just for a small number of users or us only, in cases where DietPi-Build does not support a VM type or SBC yet. In the future it may be in general a good starting point, as alternative to Armbian, as the Debian installer supports more and more SBCs.

**Comment by StephanStS** [comment]
@MichaIng: I assume the mini.iso resp. netinst option of Debian is very raw on other platforms as PCs.
I see these pages referring about it:
- https://www.debian.org/CD/netinst/ -> https://raspi.debian.net/tested-images/
- https://www.debian.org/releases/testing/arm64/ch02s01.de.html -> https://www.debian.org/ports/arm/ -> https://wiki.debian.org/Arm64Port#Hardware.2C_emulators_and_models

Finally, I came to the result that the number of supported hardware variants is not as much that dealing with this issue is much worthful.

Therefore I propose to close this issue with a "won't be considered" comment.

**Comment by MichaIng** [comment]
I agree. Also this method has become pretty obsolete now that we have `dietpi-build`. Let's close this.
