### ISSUE TITLE
DietPi Software Docs - netdata -  monitor pihole link should be removed

### ISSUE THREAD

**Issue by Nightliss** [MichaIng/DietPi-Docs#382]
Hello, 

I've been reading entry in the docs regarding netdata https://dietpi.com/docs/software/system_stats/#netdata which has a tab which links to the https://learn.netdata.cloud/guides/monitor/pi-hole-raspberry-pi describing how to use netdata to monitor pihole.

So I've spend last hour stumbling around how to make it work only to find this issue https://github.com/MichaIng/DietPi/issues/3622
mentioning that newer versions of netdata are too heavy. Current version doesn't have the required plugin https://github.com/netdata/go.d.plugin to make it work.

So it should be either removed or there should be a notice so people don't waste time searching why it isn't working :) since it also has section about enabling temp monitoring which works fine.

**Comment by MichaIng** [comment]
Fixed with this PR: #383
In the Pi-hole docs block, I replaced that part with DietPi-CloudShell, where the today night released DietPi v7.0 re-enabled full functionality for. It's not a monitor with animated graphs, but a small simple stats print, with the most important DNS query and blocking numbers.

**Comment by Nightliss** [comment]
Looks great, many thanks!
