### ISSUE TITLE
clarify section on netdata

### ISSUE THREAD

**Issue by CouldBeThis** [MichaIng/DietPi-Docs#429]
Hi,

I made a small change on a fork. I didn't want to make a PR because after reading the contrib guidelines I am not sure if you want these or not?

https://github.com/CouldBeThis/DietPi-Docs/commit/4c2a6fed381b20db4fc121744825c9322f44f8ed

If you do, I am noticing places where a bit of clarification would help, at least to a person who is not already extremely familiar with linux and servers. I will make fixes when I can work out the meaning. If you'd rather not, then that's fine too.

**Comment by MichaIng** [comment]
Many thanks, good additions.

> I didn't want to make a PR because after reading the contrib guidelines I am not sure if you want these or not?

You mean https://github.com/MichaIng/DietPi-Docs#contributing or https://dietpi.com/contribute.html? Since we want to encourage everyone to participate in any way, which part made you think we might not want a change like that? Or is there a note missing to encourage for smaller additions?

Please open the PR, which allows us to comment to individual code lines and discuss based on a concrete suggestion. Also having it merged from your fork adds you to the (Git-internal) contributors list, which is the least credit you deserve 🙂.

**Comment by CouldBeThis** [comment]
I am not very experienced at this so I am trying to follow what is being requested. On the readme for this repo and on the contribution page on the website, it is talking mostly about fixing already opened issues. So I thought maybe things were planned out and random fixes would be unhelpful. But OK, I will do it then.

**Comment by CouldBeThis** [comment]
Thank you for all the feedback, I believe I have made all the changes that were requested. Thank you for your patience.
