### ISSUE TITLE
DietPi software: Add beets description

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#508]
See also https://github.com/MichaIng/DietPi/pull/4438.

**Comment by MichaIng** [comment]
@StephanStS 
OOT: Currently the [v7.3](https://github.com/MichaIng/DietPi-Docs/milestone/2) milestone is not only for tasks that need to be done and merged with the DietPi v7.3 release, but also for tasks which we wan't to do earlier. So we then still need to "Next DietPi release" tag to block merging related PRs until DietPi release. I think we didn't think about that last meeting.

Not sure how to handle best, keep both, add a "do now"/"high priority" tag or milestone, or work more with the assignments, so that an assignment means "will be done within the next week, otherwise I will unassign myself"?
