### ISSUE TITLE
MINEos not showing webpage

### ISSUE THREAD

**Issue by zarigata** [MichaIng/DietPi-Docs#577]
![image](https://user-images.githubusercontent.com/39637452/133934914-6056aefb-e1fe-4f9a-8741-ab9f8a3f48b0.png)

so what should i do now?

**Comment by MichaIng** [comment]
Do you mean the MineOS web interface or the broken (changed to private, just recognised :thinking:) YouTube link on our documentation?

**Comment by zarigata** [comment]
![image](https://user-images.githubusercontent.com/39637452/134029359-21b635cc-53c3-4526-9a8c-bb64626c7f66.png)

not available

**Comment by MichaIng** [comment]
Link removed: #578

If you try to access the MineOS web interface of your local install, try it via `https://192.168.15.65:8443`.

**Comment by MichaIng** [comment]
Which distro version do you run?
```sh
echo $G_DISTRO_NAME
```
Due to breaking changes in Minecraft v1.17, requiring at least Java 16, it can only run on Bullseye, while earlier Minecraft versions can only run until Buster, at least as long as MineOS ships an internal solution for this (I think there was a discussion about shipping own Java binaries). If it doesn't work work despite choosing the correct Minecraft version, please open an issue at out main repository: https://github.com/MichaIng/DietPi/issues

This one here is only about the documentation: https://dietpi.com/docs/

**Comment by zarigata** [comment]
Buster

**Comment by MichaIng** [comment]
Then you need to use a Minecraft server up to v1.16 only. However, please open an issue at the other repository I linked.

**Comment by zarigata** [comment]
OOKK
