### ISSUE TITLE
Add NanoPi R2C and R2C plus to the documentation

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#652]
Assumed is that the new variants [R2C](https://wiki.friendlyarm.com/wiki/index.php/NanoPi_R2C) and [R2C](https://wiki.friendlyarm.com/wiki/index.php/NanoPi_R2C_Plus) plus are compatible to [R2S](https://wiki.friendlyarm.com/wiki/index.php/NanoPi_R2S).

Then the document https://dietpi.com/docs/hardware/#nanopi-series-friendlyarm needs to be changed.

Also the web page needs an update: https://dietpi.com/#download to add them to the R2S box.

**Comment by MichaIng** [comment]
Do you have one to test whether it's compatible? Looks like the only difference is one of the Ethernet port chips. Unlikely that it is not compatible but if we are unlucky the current device tree does not cover it or so. Since Internet is essential, we should assure both Ethernet adapters work OOTB. The eMMC of the plus variant shouldn't be an issue. Also IMHO not a blocker when at first our image works on SD card only until there is either a dedicated bootloader/kernel build or support is merged into the existing one.

**Comment by StephanStS** [comment]
> Do you have one to test whether it's compatible? Looks like the only difference is one of the Ethernet port chips. Unlikely that it is not compatible but if we are unlucky the current device tree does not cover it or so. 
No. 
I also came to this result.
Yes.

**Comment by MichaIng** [comment]
Closing this. We can reopen once someone can verify compatibility with the R2S image and we declared it so on DietPi end, or we generated a dedicated image.
