### ISSUE TITLE
Update dietpi-config docs

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi-Docs#840]
The "Firmware update" option from Advanced Options has been removed and some new options to change all network check parameters have been added to Network Options: Misc.

But should be done after #833, or based on it, I'll take care of that PR tomorrow.

**Comment by StephanStS** [comment]
Network Options: Misc:
![image](https://user-images.githubusercontent.com/57687516/216847677-6cd67965-3a2b-478b-b058-3436df2f9fde.png)
ChangeLog.txt: 
DietPi-Config | It is now possible to change the dietpi.txt network connection test settings CONFIG_CHECK_CONNECTION_IP, CONFIG_CHECK_CONNECTION_IPV6 and CONFIG_CHECK_DNS_DOMAIN via dietpi-config Network Options: Misc menu. Those are used when checking Internet access via IPv4 and IPv6 and DNS resolver functionality.

Removed firmware update: 
![image](https://user-images.githubusercontent.com/57687516/216847783-75ccd521-a890-472f-b836-9bc1b00c9563.png)
ChangeLog.txt: Nothing. 
dietpi-config history:
DietPi-Config | Remove firmware upgrade option. It is obsolete since "apt upgrade" as well as now G_AGUG do kernel package upgrades, even if new packages need to be installed for that. "apt full-upgrade"/"apt-get dist-upgrade"/G_AGDUG is required only if packages need to be removed for an upgrade.
